- hosts: all
  become: true

  vars:
    deploy_version: latest
    registry_username: undefined
    registry_password: undefined

  tasks:
    - name: "Ensure repository key is installed"
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: "Update apt"
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

    - name: "Install Docker"
      apt: name=docker-engine update_cache=yes

    - name: "Make sure Docker daemon is running"
      service: name=docker state=restarted

    - name: "Ensure python-pip is installed"
      apt: name=python-pip

    - name: "Ensure docker-py is installed"
      pip: name=docker-py

    - name: "Log into docker hub registry"
      docker_login:
        api_version: 1.18
        email: "miiro@getintodevops.com"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"

    - name: "Ensure our app container is running"
      docker_container:
        api_version: 1.18
        name: app
        state: restarted
        image: "getintodevops/hellonode:{{ deploy_version }}"
        pull: true
        env:
          APP_VERSION: "{{ deploy_version }}"
        ports:
          - "8000:8000"

    - name: "Log the deployment"
      shell: 'echo $(date) -- {{ deploy_version }} >> /var/log/deploy.log'